### ISSUE TITLE
libuv compatibility layer?

### ISSUE THREAD

**Issue by brett19** [iojs/nan#173]
Might be nice to have a compatibility layer for handling various libuv uses across node versions?  Maybe I'm the only one who uses libuv from my library, but might be commonly useful.
I have the beginnings of one already, https://github.com/brett19/libcouchbase/blob/master/plugins/io/libuv/libuv_compat.h .

**Comment by kkoopa** [comment]
There are some libuv compatibility parts in nan.h now. We can split it out into a separate file at some point if it grows in size.
