### ISSUE TITLE
NAN uses identifiers with leading underscores

### ISSUE THREAD

**Issue by agnat** [iojs/nan#219]
Leading underscores in names is a minefield. Better use trailing underscores to tag internal symbols. NAN currently uses names starting with `_N` and those are definitely reserved:

http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier

Also, consider using the `NanInternal` namespace.

**Comment by kkoopa** [comment]
fixed in 49f2333d90196d2b5f9df02a3063f1f4cd3df9cc

**Comment by elfring** [comment]
I find that [the prefix "_Nan"](https://github.com/iojs/nan/blob/36fed88af7b180418fc6d8ff3f325b6f4de7a305/nan.h#L605 "More update candidates") should also [be adjusted](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation."), shouldn't it?

**Comment by kkoopa** [comment]
Indeed. I left it out of this commit, because I was going to merge 8630ce58e73af8afee2d4b6eb0ee1bd84e1a07d7 anyway, which took care of that.
Same thing with error macros.
