### ISSUE TITLE
Allow Persistent<Object> for NanMakeCallback target

### ISSUE THREAD

**Issue by mscdex** [iojs/nan#269]
It prevents having to cast to `Handle` for every call. I'm not sure how expensive that is?

**Comment by kkoopa** [comment]
I presume you are referring to the 0.10-side of things.
A straight cast ought to be wholly free, as `Persistent` is a descendant of `Handle`. Inconvenience in having to cast is probably the main issue.

On the newer versions, `Persistent` does not descend from `Handle` and the only guaranteed safe way is by creating a new `Local` from the persistent handle. This has little overhead, although it does exist. If the `Persistent` is known not to be weak, it is possible to do a hack with a cast of the address to a `Handle *` and dereferencing it for free, but this is a minor implementation detail and better ignored.

To keep the NAN API consistent, it would then be necessary to accept `Persistent<Object>` for both versions.

Personally, I don't think using `NanNew` as in `NanMakeCallback(NanGetCurrentContext()->Global(), NanNew(callback), 1, argv);` is awfully inconvenient, but I am not opposed to adding an overload if I get a nice pull request including a test case.
