### ISSUE TITLE
Undefined for return NanEscapeScope in Node.JS

### ISSUE THREAD

**Issue by RafaelKozar** [iojs/nan#287]
Hello somebody can explain me why  "return NanEscapeScope(imageBuffer);" return undefined to variable in node.js? How I can return my imageBuffer?

NAN_METHOD(analyzeImage)
    {
        TRACE_FUNCTION;
        NanEscapableScope();

        Local<Object> imageBuffer;
        std::string   imageFile;
        Local<Function> imageCallback;
        std::string     error;
			
		

        if (NanCheck(args)
            .Error(&error)
            .ArgumentsCount(2)
            .Argument(0).IsBuffer().Bind(imageBuffer)
            .Argument(1).IsFunction().Bind(imageCallback))
        {
            NanCallback *callback = new NanCallback(imageCallback);
            NanAsyncQueueWorker(new ImageAnalyzeTask(CreateImageSource(imageBuffer), callback));
			      return NanEscapeScope(imageBuffer);
      	
        }
        else if (NanCheck(args)
            .Error(&error)
            .ArgumentsCount(2)
            .Argument(0).IsString().Bind(imageFile)
            .Argument(1).IsFunction().Bind(imageCallback))
        {
            NanCallback *callback = new NanCallback(imageCallback);
            NanAsyncQueueWorker(new ImageAnalyzeTask(CreateImageSource(imageFile), callback));
            
			//NanReturnValue(NanNew<String>("FooBar!"));
			return NanEscapeScope(imageBuffer);
			
        }
        else if (!error.empty())
        {
            NanThrowTypeError(error.c_str());
        }

         NanReturnUndefined();
    }

**Comment by kkoopa** [comment]
As this seems to be a v8-exposed method, due to the use of `NAN_METHOD`, you should do `NanReturnValue(imageBuffer);`. For the same reason, you don't need an escapable scope, but `NanScope` should suffice.

**Comment by RafaelKozar** [comment]
thank for help, but variable of return still be undefined in node.js

**Comment by RafaelKozar** [comment]
Thanks for help me ;) . I switched imageBuffer to imageFile. 
I had errors, why?

../src/modules/analyze/binding.cpp: In function ‘v8::Handle<v8::Value> cloudcv::analyzeImage(const v8::Arguments&)’:
../node_modules/nan/nan.h:1331:56: error: no matching function for call to ‘v8::HandleScope::Close(std::string&)’
 # define NanReturnValue(value) return scope.Close(value)
                                                        ^
../src/modules/analyze/binding.cpp:105:4: note: in expansion of macro ‘NanReturnValue’
    NanReturnValue(imageFile);
    ^
../node_modules/nan/nan.h:1331:56: note: candidate is:
 # define NanReturnValue(value) return scope.Close(value)
                                                        ^
../src/modules/analyze/binding.cpp:105:4: note: in expansion of macro ‘NanReturnValue’
    NanReturnValue(imageFile);
    ^
In file included from ../src/cloudcv.hpp:3:0,
                 from ../src/modules/analyze/binding.cpp:1:
/root/.node-gyp/0.10.32/deps/v8/include/v8.h:4332:10: note: template<class T> v8::Local<T> v8::HandleScope::Close(v8::Handle<T>)
 Local<T> HandleScope::Close(Handle<T> value) {
          ^
/root/.node-gyp/0.10.32/deps/v8/include/v8.h:4332:10: note:   template argument deduction/substitution failed:
In file included from ../src/cloudcv.hpp:4:0,
                 from ../src/modules/analyze/binding.cpp:1:
../node_modules/nan/nan.h:1331:56: note:   ‘std::basic_string<char>’ is not derived from ‘v8::Handle<T>’
 # define NanReturnValue(value) return scope.Close(value)
                                                        ^
../src/modules/analyze/binding.cpp:105:4: note: in expansion of macro ‘NanReturnValue’
    NanReturnValue(imageFile);
    ^
../node_modules/nan/nan.h:1331:56: error: no matching function for call to ‘v8::HandleScope::Close(std::string&)’
 # define NanReturnValue(value) return scope.Close(value)
                                                        ^
../src/modules/analyze/binding.cpp:121:4: note: in expansion of macro ‘NanReturnValue’
    NanReturnValue(imageFile);
    ^
../node_modules/nan/nan.h:1331:56: note: candidate is:
 # define NanReturnValue(value) return scope.Close(value)
                                                        ^
../src/modules/analyze/binding.cpp:121:4: note: in expansion of macro ‘NanReturnValue’
    NanReturnValue(imageFile);
    ^
In file included from ../src/cloudcv.hpp:3:0,
                 from ../src/modules/analyze/binding.cpp:1:
/root/.node-gyp/0.10.32/deps/v8/include/v8.h:4332:10: note: template<class T> v8::Local<T> v8::HandleScope::Close(v8::Handle<T>)
 Local<T> HandleScope::Close(Handle<T> value) {
          ^
/root/.node-gyp/0.10.32/deps/v8/include/v8.h:4332:10: note:   template argument deduction/substitution failed:
In file included from ../src/cloudcv.hpp:4:0,
                 from ../src/modules/analyze/binding.cpp:1:
../node_modules/nan/nan.h:1331:56: note:   ‘std::basic_string<char>’ is not derived from ‘v8::Handle<T>’
 # define NanReturnValue(value) return scope.Close(value)
                                                        ^
../src/modules/analyze/binding.cpp:121:4: note: in expansion of macro ‘NanReturnValue’
    NanReturnValue(imageFile);

Thanks.

**Comment by agnat** [comment]
Because `imageFile` is a `std::string`, not a `v8::String`. Try

````
NanReturnValue(NanNew(imageFile));
````

**Comment by rvagg** [comment]
@RafaelKozar from your email to me on this topic (btw I'm glad you filed the issue here, that's what I would have suggested you do anyway) I'm guessing that you're expecting the return to return the completed processed image. `NanAsyncQueueWorker` is going to queue the work in a separate thread but the return will return immediately, _before_ any work has even begun in the new thread (likely). So the _real_ return will happen as a response from that worker which will need to call its callback with the image buffer, complete.

My apologies if I haven't understood your issue correctly.

**Comment by RafaelKozar** [comment]
Yes, this is exactly what I want, but I don't know how to do it. 
Could you give me some examples for this.

Thanks

**Comment by ReklatsMasters** [comment]
This is simple example. How can i do that?

```cpp
Handle<Value> foo() {
    NanEscapableScope();

    // some code ... 
    bool err = false;
    Local<Value> data = NanEscapeScope( bar(&err) );

    if (err) {
        // return undefined ???
    }

    return NanEscapeScope( data );
}
```

**Comment by kkoopa** [comment]
return NanUndefined should work
