### ISSUE TITLE
External Implementation in node 0.10 and 0.12

### ISSUE THREAD

**Issue by vsacheti** [iojs/nan#291]
Not sure if its an issue or mistake on my part, but just wanted to run with you something.

In node10, prior to nan, our native method was returning an external object, something like this
`return scope.Close(External::Wrap(handle));`
with nan, now I have changed this it to 
`NanReturnValue(NanNew<External>(handle))`
This works compile time in both node10 and node12, 
but fails runtime in node10, with error something like 
```
# API call returned invalid object
#==== Stack trace ============================================
Security context: 0x316ec8757281 <JS Object>#0#
```
Although it works fine in node12.
On Looking at v8.h for node10, it looks like they suggest to use Wrap/Unwrap.
(from the documentation)
* The Wrap function V8 will return the most optimal Value object wrapping the
 * C++ void*.

Should nan, use Wrap for node10 and External::New for node12?

**Comment by kkoopa** [comment]
Hmm, might be, but I guess `Unwrap` needs to be used if `Wrap` has been used and unfortunately that method has been removed in new versions of v8. This implies that there is a need to also add a `NanUnwrapExternal` which would call `Value()` or `Unwrap()` on the `External` handle according to version.

**Comment by kkoopa** [comment]
Actually, it seems you cannot return an `External`. According to [the documentation](https://developers.google.com/v8/embed#dynamic), you should only use `External` on internal fields of an `Object`, not return it directly.

**Comment by bnoordhuis** [comment]
In v0.12 and io.js, you use `value.As<v8::External>()->Value()`.  You should be able to return the value from `v8::External::New()` just fine, it's essentially a property-less object with a hidden field where the pointer is stored.

**Comment by kkoopa** [comment]
The thing is that External::Wrap would make a Local<Value> from a T*. That is no longer possible. You have to do NanNew<S>(T) to convert manually.

**Comment by vsacheti** [comment]
On checking in detail, looks like node v0.10, doesn't like JavaScript Objects which are returned from the C++ layer using Local<External>.
It has some extra Foreign Type check, which rejects the JavaScript Object.

We added the following to work around that
#if (NODE_MODULE_VERSION < 12)

#define TO_EXTERNAL(sb) \
    External::Wrap(sb)
#define FROM_EXTERNAL(sb) \
    External::Unwrap(sb)

#else

#define TO_EXTERNAL(sb) \
    NanNew<External>(sb)
#define FROM_EXTERNAL(sb) \
    External::Cast(*sb)->Value()

#endif
