### ISSUE TITLE
Node Buffer from NanNewBufferHandle

### ISSUE THREAD

**Issue by tmarrinan** [iojs/nan#292]
NanNewBufferHandle returns a different object in v0.10.X and v0.12.X.
 - In v0.10.X, a SlowBuffer is the final JS object
 - In v0.12.X a Buffer is the final JS object

In order to get a Buffer in v0.10.0 it requires using #if statements to check the version

```
    Persistent<Function> NodeBuffer;
#if (NODE_MAJOR_VERSION == 0 && NODE_MINOR_VERSION == 10)
    NodeBuffer = Persistent<Function>::New(Handle<Function>::Cast(Context::GetCurrent()->Global()->Get(String::New("Buffer"))));
#endif

    ...

    Local<Object> buffer;
#if (NODE_MAJOR_VERSION == 0 && NODE_MINOR_VERSION == 10)
    node::Buffer *slowbuf = node::Buffer::New(size);
    memcpy(node::Buffer::Data(slowbuf), buf, size);
    Handle<Value> bufArgs[3] = { slowbuf->handle_, NanNew<Integer>(size), NanNew<Integer>(0) };
    buffer = NodeBuffer->NewInstance(3, bufArgs);
#else
    buffer = NanNewBufferHandle(buf, size);
#endif
```

**Comment by kkoopa** [comment]
Yes, the buffer implementation has changed. But I fail to see why this is a problem.It has always been this way.
/cc @trevnorris

**Comment by tmarrinan** [comment]
I would like my addon to trigger a callback with a Node Buffer object as the parameter. However in the current implementation, a SlowBuffer or a Buffer will be passed depending on the node version. I thought the whole point of NAN was to make the addon code work the same regardless of the node version.

**Comment by TooTallNate** [comment]
Interface-wise though, SlowBuffer and Buffer are the same. Why do you specifically _need_ a `Buffer` instance?

**Comment by tmarrinan** [comment]
Mainly because Node warns against using SlowBuffers:
"...this should used sparingly and only be a last resort after a developer has actively observed undue memory retention in their applications"

**Comment by TooTallNate** [comment]
It's only saying that about the use-case in that example above it. SlowBuffers are (were) created in C++, so there's really no point in wrapping them in a JS regular Buffer instance, it's just more overhead.

**Comment by trevnorris** [comment]
@tmarrinan don't worry about that warning. it was suggested I put that in there when I first rewrote Buffer, but it's perfectly safe to use.
