### ISSUE TITLE
How do I set object's named or numerically indexed properties?

### ISSUE THREAD

**Issue by metabench** [iojs/nan#301]
I'd like to implement a Vector object that takes numeric values, such as `vector[12] = 24`. I'd like to use getters and setters in C++.

I see `NAN_GETTER`, `NAN_SETTER`, `NAN_PROPERTY_GETTER`, `NAN_PROPERTY_SETTER`, with the property-specific methods looking most applicable, but I could not see any examples of how to use it, or enough further explanation of how to put it to use.

**Comment by kkoopa** [comment]
Why not just do this in javascript with an array?

`NAN_GETTER` and `NAN_SETTER` are accessors, https://developers.google.com/v8/embed#accesssors

`NAN_PROPERTY_GETTER` and `NAN_PROPERTY_SETTER` are named property interceptors, while `NAN_INDEX_GETTER` and `NAN_INDEX_SETTER` are indexed property interceptors https://developers.google.com/v8/embed#interceptors

https://v8docs.nodesource.com/io.js-1.2/db/d5f/classv8_1_1_object_template.html#aa90691622f01269c6a11391d372ca0c5

https://github.com/rvagg/nan/blob/master/test/cpp/settergetter.cpp

**Comment by metabench** [comment]
@kkoopa I want to do this in C++ because that's where I'm planning on having the object residing. I'm interested in getting objects/classes written in C++ working within JavaScript. Just doing it in JavaScript would likely be slower. At least I'd like to compare implementations.

Thankyou for providing those references.

`NAN_INDEX_SETTER` looks like what I'm looking for. I've written some code using it, it compiles, but I don't know where to find the index that it was given.

It does not look like others have been using this feature as my search for its use on Google only turned up NAN itself.

`NAN_INDEX_SETTER` is not currently covered by tests either.

**Comment by kkoopa** [comment]
https://github.com/rvagg/nan#api_nan_index_getter
> You get a uint32_t index and an appropriately typed args object that can act similar to the args argument to a NAN_METHOD call.

**Comment by kkoopa** [comment]
Also, I know that it is in use. https://github.com/TooTallNate/node-weak

**Comment by metabench** [comment]
Thanks for showing me that example. Unfortunately I'm running into problems with `SetIndexedPropertyHandler`. From what I can tell, a major difference between the node-weak code and what I'm looking for is that the addon provides a constructer function that gets called in JavaScript, then the property of the instance gets set through JavaScript, with the interception taking place in C++. I did not understand the V8 guide in terms of how it would translate to use of NAN

Here is the code I have that is not successfully binding the .`IndexedPropertyHandler`:

```
#include "c_vector.h"
#include <iostream>
#include <stdlib.h>

using namespace v8;
using namespace std;

Persistent<Function> CVector::constructor;

CVector::CVector(double value) : value_(value) {
}

CVector::~CVector() {
}

void CVector::Init(Handle<Object> exports) {
  NanScope();

  // Prepare constructor template
  Local<FunctionTemplate> tpl = NanNew<FunctionTemplate>(New);
  tpl->SetClassName(NanNew("CVector"));
  tpl->InstanceTemplate()->SetInternalFieldCount(1);

  tpl->SetIndexedPropertyHandler(CVector::IndexedSet, CVector::IndexedGet)
  // Prototype
  NODE_SET_PROTOTYPE_METHOD(tpl, "plusOne", PlusOne);

  NanAssignPersistent(constructor, tpl->GetFunction());
  exports->Set(NanNew("CVector"), tpl->GetFunction());
}

NAN_METHOD(CVector::New) {
  NanScope();

  if (args.IsConstructCall()) {
    // Invoked as constructor: `new MyObject(...)`
    double value = args[0]->IsUndefined() ? 0 : args[0]->NumberValue();
    CVector* obj = new CVector(value);
    obj->Wrap(args.This());

    NanReturnValue(args.This());
  } else {
    // Invoked as plain function `MyObject(...)`, turn into construct call.
    const int argc = 1;
    Local<Value> argv[argc] = { args[0] };
    Local<Function> cons = NanNew<Function>(constructor);
    NanReturnValue(cons->NewInstance(argc, argv));
  }
}

NAN_METHOD(CVector::PlusOne) {
  NanScope();
  CVector* obj = ObjectWrap::Unwrap<CVector>(args.Holder());
  obj->value_ += 1;

  NanReturnValue(NanNew(obj->value_));
}

NAN_INDEX_SETTER(CVector::IndexedSet) {
    NanScope();
    cout << "NAN_INDEX_SETTER" << endl;
    NanReturnNull();
}

NAN_INDEX_GETTER(CVector::IndexedGet) {
    NanScope();
    cout << "NAN_INDEX_GETTER" << endl;
    NanReturnNull();
}
```

And in the header:

```
#ifndef CVECTOR_H
#define CVECTOR_H

#include <nan.h>

class CVector : public node::ObjectWrap {
 public:
  static void Init(v8::Handle<v8::Object> exports);

 private:
  explicit CVector(double value = 0);
  ~CVector();

  static NAN_METHOD(New);
  static NAN_METHOD(PlusOne);
  static NAN_INDEX_SETTER(IndexedSet);
  static NAN_INDEX_GETTER(IndexedGet);
  //static NAN_INDEX_SETTER
  static v8::Persistent<v8::Function> constructor;
  double value_;
};

#endif
```

**Comment by kkoopa** [comment]
You have swapped the arguments to `SetIndexedPropertyHandler`, which in turn is not directly available from a `FunctionTemplate`, you need to access either `InstanceTemplate()` or `PrototypeTemplate()`.

```c++
#include "cvector.h"
#include <iostream>
#include <cstdlib>

using namespace v8;
using namespace std;

Persistent<Function> CVector::constructor;

CVector::CVector(double value) : value_(value) {
}

CVector::~CVector() {
}

void CVector::Init(Handle<Object> exports) {
  NanScope();

  // Prepare constructor template
  Local<FunctionTemplate> tpl = NanNew<FunctionTemplate>(New);
  tpl->SetClassName(NanNew("CVector"));
  tpl->InstanceTemplate()->SetInternalFieldCount(1);

  tpl->PrototypeTemplate()->SetIndexedPropertyHandler(CVector::IndexedGet, CVector::IndexedSet);
  // Prototype
  NODE_SET_PROTOTYPE_METHOD(tpl, "plusOne", PlusOne);

  NanAssignPersistent(constructor, tpl->GetFunction());
  exports->Set(NanNew("CVector"), tpl->GetFunction());
}

NAN_METHOD(CVector::New) {
  NanScope();

  if (args.IsConstructCall()) {
    // Invoked as constructor: `new MyObject(...)`
    double value = args[0]->IsUndefined() ? 0 : args[0]->NumberValue();
    CVector* obj = new CVector(value);
    obj->Wrap(args.This());

    NanReturnValue(args.This());
  } else {
    // Invoked as plain function `MyObject(...)`, turn into construct call.
    const int argc = 1;
    Local<Value> argv[argc] = { args[0] };
    Local<Function> cons = NanNew<Function>(constructor);
    NanReturnValue(cons->NewInstance(argc, argv));
  }
}

NAN_METHOD(CVector::PlusOne) {
  NanScope();
  CVector* obj = ObjectWrap::Unwrap<CVector>(args.Holder());
  obj->value_ += 1;

  NanReturnValue(NanNew(obj->value_));
}

NAN_INDEX_SETTER(CVector::IndexedSet) {
    NanScope();
    cout << "NAN_INDEX_SETTER" << endl;
    NanReturnNull();
}

NAN_INDEX_GETTER(CVector::IndexedGet) {
    NanScope();
    cout << "NAN_INDEX_GETTER" << endl;
    NanReturnNull();
}

NODE_MODULE(cvector, CVector::Init)
```

**Comment by Spongman** [comment]
this link: https://developers.google.com/v8/embed#accesssors appears all over the place. it's broken.
