### ISSUE TITLE
Backport thread local storage (TLS)

### ISSUE THREAD

**Issue by gagern** [iojs/nan#306]
libuv/libuv@5d2434bf71e47802841bad218d521fa254d1ca2d from joyent/libuv#904 added support for thread local storage. Would it be in scope for Nan to backport this in order to offer TLS support for node modules even when compiling against older versions of node?

This question was raised in https://github.com/polotek/libxmljs/pull/300#commitcomment-10607079 discussing gagern/libxmljs@55a686129f11fe4f9db63c7e3d0268b4cef5c45e.

If you are interested in this, I can provide a pull request. Or you can paste the relevant code yourself, once you have decided where it should go. It might make sense to declare the functions as `inline` or `static` to avoid having the same function in multiple source files, and so that dead code elimination can drop them if they are unused.

**Comment by kkoopa** [comment]
Sure. It would at least be appropriate for NAUV (NAN for UV), which does not exist as a separate project yet, so it could go with the other uv stuff of NAN for now. Please provide a PR, it might be suitable to insert the methods after [line 101](https://github.com/rvagg/nan/blob/master/nan.h#L101) and make their names match the NAN scheme.
