### ISSUE TITLE
Signature::New signature changed in V8 4.2

### ISSUE THREAD

**Issue by rvagg** [iojs/nan#308]
I'm not sure how to tackle this one cause the `NanNew` stuff has changed quite a bit since I touched it and the split across multiple files has me scratching myself.

I'm trying out io.js next which has V8 4.2.77 and am bumping in to compile problems related to the new signature of this method:

```diff
-  static Local<Signature> New(Isolate* isolate,
-                              Handle<FunctionTemplate> receiver =
-                                  Handle<FunctionTemplate>(),
-                              int argc = 0,
-                              Handle<FunctionTemplate> argv[] = 0);
+  static Local<Signature> New(
+      Isolate* isolate,
+      Handle<FunctionTemplate> receiver = Handle<FunctionTemplate>());
```

Not super-urgent but we only have a couple of weeks before this goes live.

**Comment by bnoordhuis** [comment]
Are there any serious users?  If there aren't, it's probably easier to remove it.

**Comment by kkoopa** [comment]
It was removed in [this issue](https://codereview.chromium.org/848173002). Easiest way does seem like removing the option of setting arguments for signatures. I don't think it's worth it to reimplement a `NanSignature` wrapper, as this feature is rarely used. If necessary, implementer should do argument checking themselves, as the note states.

**Comment by kkoopa** [comment]
Change https://github.com/rvagg/nan/blob/master/nan_new.h#L153 to `New( FTH receiver = FTH());`
Change https://github.com/rvagg/nan/blob/master/nan_implementation_12_inl.h#L177-182 to
```c++
Factory<v8::Signature>::return_t
Factory<v8::Signature>::New( Factory<v8::Signature>::FTH receiver) {
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver);
}
```
Change https://github.com/rvagg/nan/blob/master/nan_implementation_pre_12_inl.h#183-188 to
```c++
Factory<v8::Signature>::return_t
Factory<v8::Signature>::New( Factory<v8::Signature>::FTH receiver) {
  return v8::Signature::New(receiver);
}
```
