### ISSUE TITLE
"double free or corruption" cryptic failure

### ISSUE THREAD

**Issue by marcelo-ni** [iojs/nan#313]
Using nan to port our addon to node-v0.12.2. 
Running a simple test, we have the error in the subject. 
The README tells

`NanBufferUse` uses the `char*` passed as the backing data, and will free the
memory automatically when the weak callback is called. Keep this in mind, as
careless use can lead to "double free or corruption" and other cryptic failures.

We are not using NanBufferUse at all, but it´s obvious that same thing may arise in other places. 

How could we try to find where?

TIA

**Comment by kkoopa** [comment]
Valgrind might help in pinpointing the error. String converters are the usual suspects when it comes to memory errors, that is, making proper strings out of v8 Strings. If the code base is not too large, just scan through it for all references to `free()`, `delete` or `delete[]` and find the culprit that way. Common good practice is to set pointers to `NULL` after freeing. That way you will get a segfault if anything tries to use the pointer later.

**Comment by marcelo-ni** [comment]
Thank you! Valgrind proves invaluable. I forgot of it until you point me to. 
The first error was because an improper delete. 
Compiling with node v0.12.2 there was another error, this time because we were assigning a v8::Array directly and not thru the Factory.
