### ISSUE TITLE
NanThrowError(Handle<Value>)

### ISSUE THREAD

**Issue by kkoopa** [iojs/nan#322]
```c++
NAN_INLINE void NanThrowError(v8::Handle<v8::Value> error) {
    NanScope();
    v8::Isolate::GetCurrent()->ThrowException(error);
  }
```
This should probably be changed to
```c++
NAN_INLINE void NanThrowError(v8::Handle<v8::Value> error) {
    NanScope();
    v8::Isolate::GetCurrent()->ThrowException(v8::Exception::Error(error));
  }
```
and the same goes for the old version.

**Comment by rvagg** [comment]
:+1: but should we check to see if it's already an `Error` first though?

**Comment by kkoopa** [comment]
Indeed. Best way is adding an overload taking a Handle<Error>, doing old behavior, and making the Handle<Value> version wrap it in an Error and calling the afforementioned version.

**Comment by rvagg** [comment]
perfect
