### ISSUE TITLE
object equality?

### ISSUE THREAD

**Issue by chriseppstein** [iojs/nan#325]
I've read through the nan docs and some of the v8 docs and I don't see how to ensure that objects exposed as js objects will correctly implement equality checks. I only get a true result from equality when checking against the same instance even if the values are the same. This makes the objects not play well with the new Map class as keys.

**Comment by kkoopa** [comment]
The comparator for ES6 maps is called `SameValueZero`
https://github.com/v8/v8-git-mirror/blob/master/src/objects.cc#L870-886
https://github.com/v8/v8-git-mirror/blob/master/src/runtime.js#L783-789

From what I can tell at a glance, it only seems to work on numbers and strings, but the specs say objects should work as keys.

**Comment by kkoopa** [comment]
It appears to use the javascript implementation of `SameValueZero` https://github.com/v8/v8-git-mirror/blob/master/src/runtime.js#L783-789
As you can see, what you want is not possible in ES 6, objects are only equal if they refer to the same instance.
```js
> var map = new Map();
< undefined
> var obj = {foo : 'bar'};
< undefined
> map.set(obj, 'value');
< Map {Object {foo: "bar"} => "value"}
> map.get(obj)
< "value"
> map.get({foo : 'bar'});
< undefined
```

**Comment by bnoordhuis** [comment]
> I don't see how to ensure that objects exposed as js objects will correctly implement equality checks.

Do you mean structural equality or identity equality?  ES6 maps and sets only support the latter.

**Comment by kkoopa** [comment]
Quick as a fox.
I speculate that this could be (sort of) worked around by computing a hash based on the object properties and using that hash as the key. If two objects hash to the same value, consider them equal.

**Comment by bnoordhuis** [comment]
You would have to recurse into properties though and take into account that semantically `{ x: 1, y: 2 }` is different from `{ y: 2, x: 1 }`.  Hence why ES6 only supports identity equality: less headaches.
