### ISSUE TITLE
Nan incompatibility with iojs-2

### ISSUE THREAD

**Issue by pksunkara** [iojs/nan#332]
There seems to be a change in the latest v8 used by iojs-2 that seems to be not ported to nan yet. Please check this line in travis-ci tests for more details.

https://travis-ci.org/apiaryio/protagonist/jobs/61613678#L424

**Comment by pksunkara** [comment]
Looks like the error is occurring at https://github.com/iojs/nan/blob/master/nan_implementation_12_inl.h#L180 because the following function has been removed.

```cpp
v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)
```

**Comment by kkoopa** [comment]
You're a month late. 8a2069d60147f9f4ff8c37b4ffe43ad736e04f6f

**Comment by pksunkara** [comment]
Thanks :+1:

**Comment by kkoopa** [comment]
No problem. Just update to NAN 1.8.4 in package.json
