### ISSUE TITLE
Assertion `buflen >= sz_ + term_len && "too small buffer"' failed.

### ISSUE THREAD

**Issue by accessdev** [iojs/nan#347]
My app buid with a nan native module and couchnode suddunely starting to crash.

Not sure if it is related to a recent Nan update from npm

node: ../node_modules/nan/nan.h:2044: void* _NanRawString(v8::Handle<v8::Value>, Nan::Encoding, size_t*, void*, size_t, int): Assertion `buflen >= sz_ + term_len && "too small buffer"' failed.

on the current revision there is no assert on line 2044 so not sure what to do.

**Comment by kkoopa** [comment]
What current revision? Nothing has changed in that deprecated functionality. The assertion just chechs that a buffer of sufficient size was provided. Nothing wrong here.

**Comment by ad34** [comment]
not sure what is the root code , I use couchnode 2.0.8 which rely on nan 1.7.0 and a custom module which was build with 1.8.4, I suppose that this module doesnt throw the assert as with 1.8.4 line 2044 is a closing bracket.

The thing is that my nodejs app now crash very fast with this message displayed in the console, and no callstack, so it can be tricky to debug.

Only a few edits where made in the nodejs code yesturday.

I use node.js 0.12.2 on centos 6.5 but also saw yesturday a smiliar assert in a windows mesage box on my windows workstation while developing. I made a screenshot, but can send it only on next monday when I'm back to work, I m off for a few days.

**Comment by ad34** [comment]
just saw this, https://issues.couchbase.com/browse/JSCBC-226?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel  it's probably the issue , problem is that I still have the issue with couchnode 2.0.8. anyway looks like a couchbase issue.
